from __future__ import annotations

from typing import Any, Callable, Protocol

from contracts.signals import SubscriptionHandle


class AppStateService(Protocol):
    def state_set(self, key: str, value: Any) -> None: ...
    def state_get(self, key: str) -> Any: ...
    def state_delete(self, key: str) -> None: ...
    def state_observe(self, key: str, callback: Callable[[Any], None]) -> SubscriptionHandle: ...
    def state_unobserve(self, handle: SubscriptionHandle) -> None: ...
